[component]
structures = [ "content_blocks" ]
label = "seleccion-estado"
description = "Seleccion estado"
icon = "wysiwyg"
tags = ["Content"]

[props]
title = "Selecciona tu estado"
description_html = "I show only my best works built completely with passion, simplicity, and creativity!"
link_url = "/projects"
show_projects = true